/**
 * ══════════════════════════════════════════════════════════════════════════
 * THE n8n PACKAGE (n8n/workflows/*.json).
 *
 * These workflows are generated by `node n8n/build.mjs` and imported into a
 * shared n8n instance. What is asserted here is what would hurt if it slipped:
 * a dangling connection, an Execute Workflow node pointing at an id that does
 * not exist in the package, a secret pasted into a node, a workflow that
 * escapes the BoLaGio namespace on the shared instance, a transport that does
 * not default to "disabled", and a committed JSON that the generator no longer
 * reproduces.
 * ══════════════════════════════════════════════════════════════════════════
 */

import { describe, expect, it } from 'vitest';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, readdirSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';

const ROOT = path.resolve(__dirname, '..');
const WORKFLOW_DIR = path.join(ROOT, 'n8n', 'workflows');
const BUILD_SCRIPT = path.join(ROOT, 'n8n', 'build.mjs');
const ERROR_HANDLER_NAME = 'BoLaGio · Error Handler';

interface Node {
  parameters: Record<string, unknown>;
  id: string;
  name: string;
  type: string;
  typeVersion: number;
  position: [number, number];
  credentials?: Record<string, { id: string; name: string }>;
}

interface Workflow {
  name: string;
  id: string;
  nodes: Node[];
  connections: Record<string, { main: Array<Array<{ node: string; type: string; index: number }>> }>;
  settings: { executionOrder: string; errorWorkflow?: string };
  tags: Array<{ name: string }>;
}

const files = readdirSync(WORKFLOW_DIR).filter((f) => f.endsWith('.json')).sort();
const workflows = new Map<string, Workflow>(
  files.map((file) => [file, JSON.parse(readFileSync(path.join(WORKFLOW_DIR, file), 'utf8')) as Workflow])
);
const allWorkflows: Workflow[] = Array.from(workflows.values());
const byId = new Map<string, Workflow>(allWorkflows.map((w) => [w.id, w]));

function nodeByName(w: Workflow, name: string): Node {
  const node = w.nodes.find((n) => n.name === name);
  if (!node) throw new Error(`${w.name}: node "${name}" not found`);
  return node;
}

function findWorkflow(name: string): Workflow {
  const w = allWorkflows.find((x) => x.name === name);
  if (!w) throw new Error(`workflow "${name}" not in package`);
  return w;
}

function stringsIn(value: unknown, out: string[] = []): string[] {
  if (typeof value === 'string') out.push(value);
  else if (Array.isArray(value)) value.forEach((v) => stringsIn(v, out));
  else if (value && typeof value === 'object') Object.values(value).forEach((v) => stringsIn(v, out));
  return out;
}

/** Outputs of a Switch node (rule outputs plus the "extra" fallback), each as the set of target node names. */
function switchTargets(w: Workflow, name: string): { rules: string[]; outputs: string[][] } {
  const node = nodeByName(w, name);
  const rules = (node.parameters as { rules: { values: Array<{ outputKey: string }> } }).rules.values.map((r) => r.outputKey);
  const outputs = (w.connections[name]?.main ?? []).map((edges) => edges.map((e) => e.node).sort());
  return { rules, outputs };
}

describe('the package', () => {
  it('contains the six workflows', () => {
    expect(files).toEqual([
      'bolagio-cleaning-routing.json',
      'bolagio-error-handler.json',
      'bolagio-guest-message.json',
      'bolagio-health-poll.json',
      'bolagio-operational-alert.json',
      'bolagio-outbox-event-pump.json',
    ]);
  });

  it('is exactly what `node n8n/build.mjs` generates', () => {
    const out = mkdtempSync(path.join(tmpdir(), 'bolagio-n8n-'));
    try {
      execFileSync(process.execPath, [BUILD_SCRIPT, '--out', out], { stdio: 'pipe' });
      const generated = readdirSync(out).filter((f) => f.endsWith('.json')).sort();
      expect(generated).toEqual(files);
      for (const file of files) {
        expect(readFileSync(path.join(out, file), 'utf8'), file).toBe(readFileSync(path.join(WORKFLOW_DIR, file), 'utf8'));
      }
    } finally {
      rmSync(out, { recursive: true, force: true });
    }
  });
});

describe.each(files)('%s', (file) => {
  const w = workflows.get(file)!;

  it('is an n8n export with the required top-level shape', () => {
    expect(typeof w.name).toBe('string');
    expect(w.id).toMatch(/^[A-Za-z0-9]{16}$/);
    expect(Array.isArray(w.nodes)).toBe(true);
    expect(w.nodes.length).toBeGreaterThan(0);
    expect(w.settings.executionOrder).toBe('v1');
    for (const node of w.nodes) {
      expect(node.id).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);
      expect(node.type).toMatch(/^n8n-nodes-base\./);
      expect(typeof node.typeVersion).toBe('number');
      expect(node.position).toHaveLength(2);
      expect(node.parameters).toBeTypeOf('object');
    }
    const names = w.nodes.map((n) => n.name);
    expect(new Set(names).size).toBe(names.length);
  });

  it('stays inside the BoLaGio namespace on the shared instance', () => {
    expect(w.name.startsWith('BoLaGio · ')).toBe(true);
    expect(w.tags).toEqual([{ name: 'bolagio' }]);
    for (const node of w.nodes) {
      for (const cred of Object.values(node.credentials ?? {})) expect(cred.name.startsWith('BoLaGio ')).toBe(true);
      // Every environment variable a node reads is a BOLAGIO_ one.
      for (const text of stringsIn(node.parameters)) {
        for (const match of Array.from(text.matchAll(/\$env\.([A-Za-z0-9_]+)/g))) expect(match[1], `${node.name} reads ${match[1]}`).toMatch(/^BOLAGIO_/);
      }
    }
  });

  it('has connections whose source and target nodes exist', () => {
    const names = new Set(w.nodes.map((n) => n.name));
    for (const [source, entry] of Object.entries(w.connections)) {
      expect(names.has(source), `source ${source}`).toBe(true);
      for (const edges of entry.main) {
        for (const edge of edges) {
          expect(names.has(edge.node), `${source} → ${edge.node}`).toBe(true);
          expect(edge.type).toBe('main');
        }
      }
    }
  });

  it('resolves every Execute Workflow reference inside the package', () => {
    for (const node of w.nodes.filter((n) => n.type === 'n8n-nodes-base.executeWorkflow')) {
      const ref = node.parameters.workflowId as { __rl: boolean; mode: string; value: string };
      expect(ref.__rl).toBe(true);
      expect(ref.mode).toBe('id');
      expect(byId.has(ref.value), `${node.name} → ${ref.value}`).toBe(true);
      expect(ref.value).not.toBe(w.id);
    }
  });

  it('routes errors to the BoLaGio error workflow and never to itself', () => {
    const errorHandler = findWorkflow(ERROR_HANDLER_NAME);
    if (w.name === ERROR_HANDLER_NAME) {
      expect(w.settings.errorWorkflow).toBeUndefined();
      expect(w.nodes.some((n) => n.type === 'n8n-nodes-base.executeWorkflow')).toBe(false);
    } else {
      expect(w.settings.errorWorkflow).toBe(errorHandler.id);
    }
  });

  it('contains no secret-looking material in node parameters', () => {
    for (const node of w.nodes) {
      for (const text of stringsIn(node.parameters)) {
        expect(text, node.name).not.toContain('BEGIN PRIVATE');
        expect(text, node.name).not.toMatch(/\bsk_[A-Za-z0-9]/);
        expect(text, node.name).not.toMatch(/[0-9a-f]{32,}/i);
        expect(text, node.name).not.toMatch(/https:\/\/[a-z0-9-]+\.supabase\.co/i);
      }
    }
  });

  it('defaults every transport switch to "disabled"', () => {
    const switches = w.nodes.filter((n) => n.type === 'n8n-nodes-base.switch' && /transport/i.test(n.name));
    for (const node of switches) {
      const { rules, outputs } = switchTargets(w, node.name);
      expect(rules[0]).toBe('disabled');
      expect((node.parameters.options as { fallbackOutput: string }).fallbackOutput).toBe('extra');
      // The fallback ("extra") output is the last one and lands where "disabled" lands.
      expect(outputs).toHaveLength(rules.length + 1);
      expect(outputs[rules.length]).toEqual(outputs[0]);
      expect(outputs[0].length).toBeGreaterThan(0);
    }
    // The Code node that resolves the transport treats an unset variable as disabled.
    for (const node of w.nodes.filter((n) => n.type === 'n8n-nodes-base.code')) {
      const js = node.parameters.jsCode as string;
      if (js.includes('function resolveTransport')) expect(js).toMatch(/\$env\.BOLAGIO_[A-Z_]+_TRANSPORT \|\| 'disabled'/);
    }
  });
});

describe('the shared client', () => {
  it('is byte-identical in every Code node that talks to the backend', () => {
    const marker = '// ═══ BoLaGio internal API client';
    const end = '// ═══ end of shared client ═══';
    const copies = new Set<string>();
    for (const w of allWorkflows) {
      for (const node of w.nodes.filter((n) => n.type === 'n8n-nodes-base.code')) {
        const js = node.parameters.jsCode as string;
        if (!js.includes(marker)) continue;
        copies.add(js.slice(js.indexOf(marker), js.indexOf(end) + end.length));
      }
    }
    expect(copies.size).toBe(1);
    const client = Array.from(copies)[0];
    expect(client).toContain("createHmac('sha256'");
    expect(client).toContain("'v1:' + timestamp + ':' + rawBody");
    expect(client).toContain("'x-bolagio-timestamp'");
    expect(client).toContain("'x-bolagio-signature'");
    expect(client).toContain('$env.BOLAGIO_N8N_INTERNAL_SECRET');
    expect(client).toContain('$env.BOLAGIO_SITE_URL');
  });
});

describe('the outbox event pump', () => {
  const pump = findWorkflow('BoLaGio · Outbox Event Pump');

  it('claims as worker n8n-bolagio with the agreed batch size', () => {
    const js = nodeByName(pump, 'Claim events').parameters.jsCode as string;
    expect(js).toContain("const WORKER = 'n8n-bolagio'");
    expect(js).toContain("JSON.stringify({ action: 'claim', worker: WORKER, limit: 20 })");
    expect(js).toContain("'/api/internal/outbox'");
  });

  it('acks and fails with the same worker name', () => {
    const js = nodeByName(pump, 'Settle event (ack or fail)').parameters.jsCode as string;
    expect(js).toContain("const WORKER = 'n8n-bolagio'");
    expect(js).toContain("action: 'ack', worker: WORKER, eventId: eventId");
    expect(js).toContain("action: 'fail', worker: WORKER, eventId: eventId, error: error");
  });

  it('routes the five guest message kinds, cleaning, alerts, silent and unsupported events', () => {
    const { rules, outputs } = switchTargets(pump, 'Route by type');
    expect(rules).toEqual([
      'guest:booking_confirmation',
      'guest:prearrival',
      'guest:checkin',
      'guest:checkout',
      'guest:review_request',
      'cleaning',
      'alert',
      'silent',
      'unsupported',
    ]);
    expect(outputs[0]).toEqual(['Guest Message · Confirmation']);
    expect(outputs[1]).toEqual(['Guest Message · Pre-arrival']);
    expect(outputs[2]).toEqual(['Guest Message · Check-in']);
    expect(outputs[3]).toEqual(['Guest Message · Check-out']);
    expect(outputs[4]).toEqual(['Guest Message · Review request']);
    expect(outputs[5]).toEqual(['Cleaning Routing']);
    expect(outputs[6]).toEqual(['Operational Alert']);
    expect(outputs[7]).toEqual(['Handled silently']);
    expect(outputs[8]).toEqual(['Reject unsupported event']);
    expect(outputs[9]).toEqual(['Reject unsupported event']); // fallback
    const guest = findWorkflow('BoLaGio · Guest Message');
    for (const name of outputs.slice(0, 5).flat()) {
      expect((nodeByName(pump, name).parameters.workflowId as { value: string }).value).toBe(guest.id);
    }
    expect(nodeByName(pump, 'Reject unsupported event').parameters.jsCode).toContain("error: 'unsupported type/version'");
  });

  it('settles every handled event and loops back for the next one', () => {
    const settle = 'Settle event (ack or fail)';
    const handlers = pump.nodes.filter((n) => /^Guest Message ·|^Cleaning Routing$|^Operational Alert$|^Handled silently$|^Reject unsupported event$/.test(n.name));
    expect(handlers).toHaveLength(9);
    for (const h of handlers) expect(pump.connections[h.name].main[0].map((e) => e.node)).toEqual([settle]);
    expect(pump.connections[settle].main[0].map((e) => e.node)).toEqual(['Loop over events']);
  });
});

describe('the guest message sub-workflow', () => {
  const guest = findWorkflow('BoLaGio · Guest Message');

  it('prepares and completes through /api/internal/messages and never sends outside "claimed"', () => {
    const prepare = nodeByName(guest, 'Prepare message').parameters.jsCode as string;
    expect(prepare).toContain("action: 'prepare'");
    expect(prepare).toContain("'/api/internal/messages'");
    const complete = nodeByName(guest, 'Complete delivery').parameters.jsCode as string;
    expect(complete).toContain("action: 'complete'");
    const claimed = nodeByName(guest, 'Claimed?');
    const trueBranch = guest.connections['Claimed?'].main[0].map((e) => e.node);
    const falseBranch = guest.connections['Claimed?'].main[1].map((e) => e.node);
    expect(claimed.type).toBe('n8n-nodes-base.if');
    expect(trueBranch).toEqual(['Messaging transport']);
    expect(falseBranch).toEqual(['Acknowledge without sending']);
  });

  it('uses the test provider only on the test transport and the disabled provider on disabled', () => {
    expect(nodeByName(guest, 'Simulate send (test transport)').parameters.jsCode).toContain("provider: 'test', providerMessageId: 'test-' + item.deliveryId");
    expect(nodeByName(guest, 'Skip (transport disabled)').parameters.jsCode).toContain("outcome: 'skipped', provider: 'disabled'");
    const { rules, outputs } = switchTargets(guest, 'Messaging transport');
    expect(rules).toEqual(['disabled', 'test', 'smtp']);
    expect(outputs[1]).toEqual(['Simulate send (test transport)']);
    expect(outputs[2]).toEqual(['Send e-mail (SMTP)']);
  });

  it('sends SMTP mail only through the "BoLaGio SMTP" credential and BOLAGIO_MAIL_FROM', () => {
    const smtp = nodeByName(guest, 'Send e-mail (SMTP)');
    expect(smtp.type).toBe('n8n-nodes-base.emailSend');
    expect(smtp.credentials).toEqual({ smtp: { id: expect.any(String), name: 'BoLaGio SMTP' } });
    expect(smtp.parameters.fromEmail).toBe('={{ $env.BOLAGIO_MAIL_FROM }}');
    expect(smtp.parameters.toEmail).toBe('={{ $json.message.to }}');
  });
});

describe('the cleaning routing sub-workflow', () => {
  it('keys the work item on the reference and maps required/rescheduled to upsert, cancelled to cancel', () => {
    const cleaning = findWorkflow('BoLaGio · Cleaning Routing');
    const js = nodeByName(cleaning, 'Build work item').parameters.jsCode as string;
    expect(js).toContain("key: 'bolagio:turnover:' + reference");
    expect(js).toContain("event.cleaningAction === 'cancel' ? 'cancel' : 'upsert'");
    const pump = findWorkflow('BoLaGio · Outbox Event Pump');
    const classify = nodeByName(pump, 'Classify event').parameters.jsCode as string;
    expect(classify).toContain('"cleaning.required": "upsert"');
    expect(classify).toContain('"cleaning.rescheduled": "upsert"');
    expect(classify).toContain('"cleaning.cancelled": "cancel"');
    const webhook = nodeByName(cleaning, 'POST to cleaning webhook');
    expect(webhook.parameters.url).toBe('={{ $env.BOLAGIO_CLEANING_WEBHOOK_URL }}');
  });
});

describe('the health poll', () => {
  it('polls every 5 minutes, keeps state in static data and alerts only on change', () => {
    const health = findWorkflow('BoLaGio · Health Poll');
    const trigger = nodeByName(health, 'Every 5 minutes');
    expect(trigger.type).toBe('n8n-nodes-base.scheduleTrigger');
    expect(trigger.parameters).toEqual({ rule: { interval: [{ field: 'minutes', minutesInterval: 5 }] } });
    const js = nodeByName(health, 'Poll health and diff state').parameters.jsCode as string;
    expect(js).toContain("$getWorkflowStaticData('global')");
    expect(js).toContain("bolagioRequest('GET', '/api/internal/health', '')");
    expect(js).toContain('const FAILURES_BEFORE_ALERT = 2');
    expect(js).toContain("'HEALTH_ALL_CLEAR'");
    expect(js).toContain("'HEALTH_NO_VERDICT'");
  });
});

describe('the error handler', () => {
  it('starts from an Error Trigger, ignores itself and non-BoLaGio workflows, and delivers directly', () => {
    const handler = findWorkflow(ERROR_HANDLER_NAME);
    expect(nodeByName(handler, 'On workflow error').type).toBe('n8n-nodes-base.errorTrigger');
    const js = nodeByName(handler, 'Shape error alert').parameters.jsCode as string;
    expect(js).toContain(`const ERROR_HANDLER_ID = '${handler.id}'`);
    expect(js).toContain("if (String(workflow.id || '') === ERROR_HANDLER_ID) return [];");
    expect(js).toContain("startsWith('BoLaGio ·')");
  });
});
